refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{f}:{L}] {h({l})} [{M}] - {m}{n}"
  requests:
    kind: rolling_file
    path: "logs/requests.log"
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{f}:{L}] {h({l})} [{M}] - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 mb
      roller:
        kind: fixed_window
        pattern: 'logs/requests.log.{}'
        base: 1
        count: 5

root:
  level: debug
  appenders:
    - stdout
    - requests
